#!/bin/sh -e
case "$1" in
    remove)
	update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/xentaos-text/xentaos-text.plymouth

	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/xentaos-logo/xentaos-logo.plymouth

	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	;;

    purge)
	;;

    upgrade|failed-upgrade|disappear)
	;;

    abort-install|abort-upgrade)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac

exit 0
